spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: ${PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
app:
  scheduling:
    enabled: false
    period: 20000
    percentage: 10.1
    optimization: true
rest:
  currency-service:
    mock:
      enabled: false
    host: http://localhost:8081 #хост второго сервиса
    methods:
      get-currency: /api/v1/currencies #урл эндпоинта с курсами для GET запроса

  account-service:
    mock:
      enabled: false
    host: http://localhost:8082
    methods:
      get-account-num: /api/v1/account/account-num

  crm-service:
    mock:
      enabled: false
    host: http://localhost:8083
    methods:
      get-inn: /api/v1/inn
s3:
  credentials:
    accessKey: test
    secretKey: test
  endpoint: http://localhost:4566
  bucket-name: product-image-bucket
  region: us-east-1