spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: ${PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
app:
  scheduling:
    enabled: true
    period: 20000
    percentage: 10.1
    optimization: true
currency-service:
  mock: false
  host: http://localhost:8081 #хост второго сервиса
  methods:
    get-currency: /api/v1/currencies #урл эндпоинта с курсами для GET запроса