spring:
  datasource:
    url: jdbc:h2:mem:warehouse
    driver-class-name: org.h2.Driver
    username: username
    password: ${PWD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: false